### ISSUE TITLE
Question: How can we delete files created after trimming.

### ISSUE THREAD

**Issue by AnsOfficial** [maitrungduc1410/react-native-video-trim#21]
How can we delete files created after trimming
because I noticed increased App data @maitrungduc1410

**Comment by maitrungduc1410** [comment]
At the moment files stored in cache and auto deleted after sometime

But I'll push update to support manually delete files

**Comment by ibelgin** [comment]
@maitrungduc1410 In Android there is an issue with this. when I navigate to the next screen. the file gets deleted and I get the below error message.

 Image source "/storage/emulated/0/Android/data/io.icare/cache/trimmedVideo_20240119_205159.mp4" doesn't exist
 
 but it's working fine on iOS. is there any solution for this getting autodeleted?

**Comment by maitrungduc1410** [comment]
> @maitrungduc1410 In Android there is an issue with this. when I navigate to the next screen. the file gets deleted and I get the below error message.
> 
> Image source "/storage/emulated/0/Android/data/io.icare/cache/trimmedVideo_20240119_205159.mp4" doesn't exist
> 
> but it's working fine on iOS. is there any solution for this getting autodeleted?

I'm working on some major update which will resolve this issue

**Comment by maitrungduc1410** [comment]
Hi @AnsOfficial  @ibelgin , please upgrade to `1.0.12`, remember to re-run `pod install`

From now for iOS + Android, file will be stored in app storage instead of cached dir, and it won't be deleted by system anymore.

Also you have control of listing+delete any file you want using:
```js
cleanFiles() // delete all files in app storage
deleteFile(someFilePath) // delete a file in app storage
listFiles() // list all files in app storage
```

**Comment by ibelgin** [comment]
@maitrungduc1410 Thank you. Let me check on it.

**Comment by maitrungduc1410** [comment]
Hi @ibelgin 

 `rc` (return code) is 1, which is unsuccessful.

Can you try with another video?

If possible can you provide me the input file which is having issue?

**Comment by ibelgin** [comment]
Sure.

**Comment by ibelgin** [comment]
@maitrungduc1410 It's working on Android but the issue is with ios now I gave the maxDuration as 5 but the video is getting trimmed to 6 seconds the first second is black.

<img width="380" alt="Screenshot 2024-01-24 at 15 53 15" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/61349423/3bb35167-a5c5-4b70-9c77-2cc85b6d4850">

<img width="397" alt="Screenshot 2024-01-24 at 15 53 36" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/61349423/bc54dc5c-4369-4f24-88f4-b1a9dbc980f5">

**Comment by maitrungduc1410** [comment]
@ibelgin  this is known issue when trimming using FFMPEG: https://superuser.com/questions/1222801/black-frames-at-beginning-of-video-file-when-file-cut

basically it happens when the starting time does not correspond to an [I-frame](https://en.wikipedia.org/wiki/Intra-frame_coding)

I'm trying to resolve this, will update

**Comment by ibelgin** [comment]
@maitrungduc1410 Thank you.

**Comment by ibelgin** [comment]
@maitrungduc1410 can this issue be resolved ?

**Comment by maitrungduc1410** [comment]
hi @ibelgin I fixed the issue, it's working now, please upgrade to `1.0.16` and try again.

this is what I figured out when using FFMPEG:
```shell
# has black frames
ffmpeg -i input.MOV -ss 00:00:00 -to 00:00:30 -c copy output1.mp4

# works, no black frame
ffmpeg -ss 00:00:00 -to 00:00:30 -i input.MOV -c copy output2.mp4
```

Original can be found [here](https://video.stackexchange.com/a/25633/30149)

**Comment by ibelgin** [comment]
@maitrungduc1410 Hey Thank you! it's working perfectly.
