### ISSUE TITLE
Full Background Not Covered in iPhone 15 Pro Max

### ISSUE THREAD

**Issue by shiyansiva** [maitrungduc1410/react-native-video-trim#43]
@maitrungduc1410  When I open it, the video trim screen doesn't fully cover the background. Is there a way to make it cover the whole background?

![IMG_0494](https://github.com/maitrungduc1410/react-native-video-trim/assets/35214422/cd913930-3bd2-4d8a-af3c-25e28e81e0d2)

Once Again Thank you very much for making awesome library!

**Comment by maitrungduc1410** [comment]
@shiyansiva  this is completely controlled by UIVideoPlayerController from the platform.

It's based on your video dimension and determines how to show.

and from my point of view: your video is landscape, it's not good if you make it fullscreen

**Comment by shiyansiva** [comment]
> @shiyansiva this is completely controlled by UIVideoPlayerController from the platform.
> 
> It's based on your video dimension and determines how to show.
> 
> and from my point of view: your video is landscape, it's not good if you make it fullscreen

@maitrungduc1410  I just want to make the modal taller, not change the video. The top of the video trim modal isn't covering the content behind it.

**Comment by maitrungduc1410** [comment]
I'll push an update for this

**Comment by maitrungduc1410** [comment]
@shiyansiva pls upgrade to `1.0.18`, added `fullScreenModalIOS`

```js
showEditor(url, {
  fullScreenModalIOS: true,
})
```

**Comment by Lakston** [comment]
using v3.0.2 at the moment, I tried updating to v5+ but apparently you need to be on the new arch (or there are bugs because barely anything was working)
this was taken with a samsung s21
Github wont let me upload my mp4 so I compressed it, you can see at the top you can see below the trim modal

(btw as you can see I changed the colors of the trim borders to white by patching the library myself, having a variable where we can enter a color to override the default yellow would be very nice :) )

[ScreenRecording.mp4.zip](https://github.com/user-attachments/files/22118366/ScreenRecording.mp4.zip)

**Comment by maitrungduc1410** [comment]
@Lakston this is how it looks on my s21

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/5ee8fd4b-26a5-4840-81aa-afa62a651439" />

---

the fullscreen dialog on Android is too tricky to cover all the cases, i remember I tried to fixed this in the past but it led to content from bottom is shifted.

that's why I decided to leave it default to the OS
